Implemented Number operations
Coffee-Hotel-Spa/shaell-interpreter pull request #26
Opened 2022-03-30 10:48 UTC by alexsteffensen

Both arithmetic and logical

2022-03-30 11:12 UTC, JE-FH requested changes

2022-03-30 11:55 UTC, alexsteffensen commented on ShaellLang/ExecutionVisitor.cs
> +        return new Number(int.Parse(num));
skumbad

2022-03-30 11:56 UTC, alexsteffensen commented on ShaellLang/ExecutionVisitor.cs
> +        return new Number(int.Parse(num));
skumbad

2022-03-30 11:56 UTC, JE-FH commented on ShaellLang/ExecutionVisitor.cs
> +        return new Number(int.Parse(num));
Ostemad

2022-03-30 12:01 UTC, alexsteffensen commented on ShaellLang/Number.cs
> +                return new Number(a.ToInteger() - b.ToInteger());
![](http://www.funny-emoticons.com/files/smileys-emoticons/funny-emoticons/67-aye-aye-sir.png)

2022-03-30 13:29 UTC, JE-FH commented on ShaellLang/Number.cs
> +                return new Number(a.ToInteger() - b.ToInteger());
Det tror jeg ikke, ellers så bare råb pik og vent med det til shæll+-

2022-03-31 07:31 UTC, JE-FH requested changes

2022-03-31 07:31 UTC, JE-FH commented on ShaellLang/Number.cs
> +                return new Number(a.ToInteger() * b.ToInteger());
Kan den ikke bare return direkte fra try så bare sig,`return checked(a.ToInteger() * b.ToInteger())`. Også det samme de andre steder

2022-03-31 07:37 UTC, JE-FH approved these changes
# LGTM

2022-03-31 07:37 UTC, merged